keys:
  - &user age1ghs3a7lxt8hduwa5dcym5cumv5kuj2xxq7uxqsvfmzj438tths0sx5s0t3
  - &laptop age1z7myt7u792ksk4ym82vyr3zcq2pqxpvrc3srkhkwfq3uz2m2evcsnvwv0j
  - &desktop age16evxrv8apm5gnn6rx06r89md54yj80epyq25wgq4tcwcsz6vaf2sh0lte2
  - &server age1mjkz9psplks5z4xewxamqxxw6g0mp065gn0la8vrztmpzxd68auq7k2y8j
creation_rules:
  - path_regex: secrets/shared\.yaml$
    key_groups:
      - age:
          - *user
          - *laptop
          - *desktop

  - path_regex: secrets/hosts/laptop\.yaml$
    key_groups:
      - age:
          - *user
          - *laptop

  - path_regex: secrets/hosts/desktop\.yaml$
    key_groups:
      - age:
          - *user
          - *desktop

  - path_regex: secrets/hosts/server\.yaml$
    key_groups:
      - age:
          - *user
          - *server

  - path_regex: secrets/device-keys/.*\.txt$
    key_groups:
      - age:
          - *user


  - path_regex: secrets/bootstrap.txt$
    key_groups:
      - age:
          - *user
